name: guess_word_ua
description: Ukrainian version of a Wordle game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.5+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  html: ^0.15.5
  lottie: ^3.3.1
  rate_my_app: ^2.3.1
  share_plus: ^10.1.4
  intl: ^0.20.2
  screenshot: ^3.0.0
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  image: ^4.5.3
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^19.0.0
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  flutter_animate: ^4.5.2
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: game_font
      fonts:
        - asset: fonts/MPLUSRounded1c-Medium.ttf