name: guess_word_ua
description: Ukrainian version of a Wordle game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  http: ^0.13.4
  html: ^0.15.0
  lottie: ^1.3.0
  flutter_neumorphic: ^3.2.0
  rate_my_app: ^1.1.3
  share_plus: ^4.0.10
  intl: ^0.17.0
  screenshot: ^1.2.3
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  image: ^3.2.0
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^9.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: game_font
      fonts:
        - asset: fonts/MPLUSRounded1c-Medium.ttf