name: guess_word_ua
description: Ukrainian version of a Wordle game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.3+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  http: ^1.1.0
  html: ^0.15.0
  lottie: ^2.6.0
  rate_my_app: ^2.0.0
  share_plus: ^7.1.0
  intl: ^0.18.1
  screenshot: ^2.1.0
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  image: ^4.0.17
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^15.1.0+1
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.2
  flutter_animate: ^4.3.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: game_font
      fonts:
        - asset: fonts/MPLUSRounded1c-Medium.ttf