name: guess_word_ua
description: Ukrainian version of a Wordle game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.4+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  http: ^1.2.2
  html: ^0.15.4
  lottie: ^3.1.2
  rate_my_app: ^2.2.0
  share_plus: ^9.0.0
  intl: ^0.19.0
  screenshot: ^3.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  image: ^4.2.0
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^17.2.1+2
  flutter_timezone: ^2.1.0
  timezone: ^0.9.4
  flutter_animate: ^4.5.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: game_font
      fonts:
        - asset: fonts/MPLUSRounded1c-Medium.ttf